export const SELECT_COURSE = 'SELECT_COURSE';
export const UNSELECT_COURSE = 'UNSELECT_COURSE';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const DISPLAY_NOTIFICATION_DRAWER = 'DISPLAY_NOTIFICATION_DRAWER';
export const HIDE_NOTIFICATION_DRAWER = 'HIDE_NOTIFICATION_DRAWER';